CLASS_TRANSLATIONS = {
    "aerosol_cans": "Latas de aerossol",
    "aluminum_food_cans": "Latas de alimentos (alumínio)",
    "aluminum_soda_cans": "Latas de refrigerante (alumínio)",
    "cardboard_boxes": "Caixas de papelão",
    "cardboard_packaging": "Embalagens de papelão",
    "clothing": "Roupas",
    "coffee_grounds": "Borra de café",
    "disposable_plastic_cutlery": "Talheres plásticos descartáveis",
    "eggshells": "Cascas de ovo",
    "food_waste": "Restos de comida",
    "glass_beverage_bottles": "Garrafas de bebida (vidro)",
    "glass_cosmetic_containers": "Frascos de cosméticos (vidro)",
    "glass_food_jars": "Potes de vidro para alimentos",
    "magazines": "Revistas",
    "newspaper": "Jornal",
    "office_paper": "Papel de escritório",
    "paper_cups": "Copos de papel",
    "plastic_cup_lids": "Tampas plásticas de copos",
    "plastic_detergent_bottles": "Frascos de detergente (plástico)",
    "plastic_food_containers": "Potes plásticos de alimentos",
    "plastic_shopping_bags": "Sacolas plásticas",
    "plastic_soda_bottles": "Garrafas PET",
    "plastic_straws": "Canudos plásticos",
    "plastic_trash_bags": "Sacos de lixo (plástico)",
    "plastic_water_bottles": "Garrafas de água (plástico)",
    "shoes": "Calçados",
    "steel_food_cans": "Latas de alimentos (aço)",
    "styrofoam_cups": "Copos de isopor",
    "styrofoam_food_containers": "Marmitas de isopor",
    "tea_bags": "Saquinhos de chá"
}
